"""update profile id to string for clerk

Revision ID: c4de1acb9b66
Revises: 001_create_all_tables
Create Date: 2026-03-07 14:37:11.580733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4de1acb9b66'
down_revision = '001_create_all_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('applications_profile_id_fkey', 'applications', type_='foreignkey')
    op.drop_constraint('projects_profile_id_fkey', 'projects', type_='foreignkey')

    op.alter_column('applications', 'profile_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False,
               postgresql_using='profile_id::varchar')
    op.create_index(op.f('ix_applications_gmail_thread_id'), 'applications', ['gmail_thread_id'], unique=False)
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False,
               postgresql_using='id::varchar')
    op.alter_column('projects', 'profile_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False,
               postgresql_using='profile_id::varchar')

    op.create_foreign_key('applications_profile_id_fkey', 'applications', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key('projects_profile_id_fkey', 'projects', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_profile_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('applications_profile_id_fkey', 'applications', type_='foreignkey')

    op.alter_column('projects', 'profile_id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='profile_id::uuid')
    op.alter_column('profiles', 'id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.drop_index(op.f('ix_applications_gmail_thread_id'), table_name='applications')
    op.alter_column('applications', 'profile_id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='profile_id::uuid')

    op.create_foreign_key('projects_profile_id_fkey', 'projects', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key('applications_profile_id_fkey', 'applications', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###